name: Daily Auto Update

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: 1. 저장소 코드 불러오기
        uses: actions/checkout@v4 # v3에서 v4로 업데이트

      - name: 2. 파이썬 가상 환경 설정
        uses: actions/setup-python@v5 # v4에서 v5로 업데이트
        with:
          python-version: '3.10'

      - name: 3. 필요한 패키지 조립
        run: pip install -r requirements.txt

      - name: 4. 데이터 수집 및 AI 요약 스크립트 실행
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        run: python main.py

      - name: 5. 새로 갱신된 data.json 파일을 깃허브에 자동 저장
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "일간 데이터 자동 업데이트 완료" || exit 0
          git push
